name: Validating Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.6 # Change this to your desired Terraform version

    - name: Configure AWS Access Key ID
      run: echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV

    - name: Initialize Terraform (Ensure Modules are Installed)
      run: terraform init -upgrade  # Ensures modules are installed

    - name: Validate Terraform Configuration
      run: terraform validate
