name: Validating Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.6

    - name: Configure AWS Access Key ID
      run: echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV

    - name: Initialize Terraform
      run: terraform init

  terraform-validate:
    runs-on: ubuntu-latest
    needs: terraform-init  # This ensures 'terraform validate' runs only after 'terraform init' completes
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.6

    - name: Configure AWS Access Key ID
      run: echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV

    - name: Validate Terraform Configuration
      run: terraform validate
