name: Validating Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.6 # Change this to your desired Terraform version

    - name: Configure AWS Access Key ID
      run: echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV

    - name: Initialize Terraform (Ensure Modules are Installed)
      run: terraform init -upgrade  # Ensures modules are installed

  terraform-validate:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.6 # Change this to your desired Terraform version

    - name: Initialize Terraform (Ensure Modules are Installed)
      run: terraform init  # Ensures modules are installed


    - name: terraform validate
      run: terraform validate

